version: '3.8'

services:
  # MySQL Database service
  mysql:
    image: mysql:8.0
    container_name: bbc_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bbc_test
      MYSQL_USER: bbc_user
      MYSQL_PASSWORD: bbc_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - golf_coaching_network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Backend FastAPI service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: golf_coaching_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/uploads:/app/uploads
      - ./backend/.env:/app/.env
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    networks:
      - golf_coaching_network
    restart: unless-stopped

  # Frontend Next.js service
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: golf_coaching_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - golf_coaching_network
    restart: unless-stopped

  # Nginx proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: golf_coaching_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/uploads:/usr/share/nginx/html/uploads
    depends_on:
      - backend
      - frontend
    networks:
      - golf_coaching_network
    restart: unless-stopped
    profiles:
      - production

networks:
  golf_coaching_network:
    driver: bridge

volumes:
  uploads_data:
  db_data: